import { VisualQueryBinary } from './shared/LokiAndPromQueryModellerBase';
import { QueryBuilderLabelFilter, QueryBuilderOperation } from './shared/types';

/**
 * Visual query model
 */
export interface PromVisualQuery {
  metric: string;
  labels: QueryBuilderLabelFilter[];
  operations: QueryBuilderOperation[];
  binaryQueries?: PromVisualQueryBinary[];
}

export type PromVisualQueryBinary = VisualQueryBinary<PromVisualQuery>;

export enum PromVisualQueryOperationCategory {
  Aggregations = 'Aggregations',
  RangeFunctions = 'Range functions',
  Functions = 'Functions',
  BinaryOps = 'Binary operations',
  Trigonometric = 'Trigonometric',
  Time = 'Time Functions',
}

export enum PromOperationId {
  Absent = 'absent',
  AbsentOverTime = 'absent_over_time',
  Acos = 'acos',
  Acosh = 'acosh',
  Asin = 'asin',
  Asinh = 'asinh',
  Atan = 'atan',
  Atanh = 'atanh',
  Avg = 'avg',
  AvgOverTime = 'avg_over_time',
  BottomK = 'bottomk',
  Ceil = 'ceil',
  Changes = 'changes',
  Clamp = 'clamp',
  ClampMax = 'clamp_max',
  ClampMin = 'clamp_min',
  Cos = 'cos',
  Cosh = 'cosh',
  Count = 'count',
  CountOverTime = 'count_over_time',
  CountValues = 'count_values',
  DayOfMonth = 'day_of_month',
  DayOfWeek = 'day_of_week',
  DaysInMonth = 'days_in_month',
  Deg = 'deg',
  Delta = 'delta',
  Deriv = 'deriv',
  Exp = 'exp',
  Floor = 'floor',
  Group = 'group',
  HistogramQuantile = 'histogram_quantile',
  HoltWinters = 'holt_winters',
  Hour = 'hour',
  Idelta = 'idelta',
  Increase = 'increase',
  Irate = 'irate',
  LabelJoin = 'label_join',
  LabelReplace = 'label_replace',
  LastOverTime = 'last_over_time',
  Ln = 'ln',
  Log10 = 'log10',
  Log2 = 'log2',
  Max = 'max',
  MaxOverTime = 'max_over_time',
  Min = 'min',
  MinOverTime = 'min_over_time',
  Minute = 'minute',
  Month = 'month',
  Pi = 'pi',
  PredictLinear = 'predict_linear',
  PresentOverTime = 'present_over_time',
  Quantile = 'quantile',
  QuantileOverTime = 'quantile_over_time',
  Rad = 'rad',
  Rate = 'rate',
  Resets = 'resets',
  Round = 'round',
  Scalar = 'scalar',
  Sgn = 'sgn',
  Sin = 'sin',
  Sinh = 'sinh',
  Sort = 'sort',
  SortDesc = 'sort_desc',
  Sqrt = 'sqrt',
  Stddev = 'stddev',
  StddevOverTime = 'stddev_over_time',
  Sum = 'sum',
  SumOverTime = 'sum_over_time',
  Tan = 'tan',
  Tanh = 'tanh',
  Time = 'time',
  Timestamp = 'timestamp',
  TopK = 'topk',
  Vector = 'vector',
  Year = 'year',
  // Binary ops
  Addition = '__addition',
  Subtraction = '__subtraction',
  MultiplyBy = '__multiply_by',
  DivideBy = '__divide_by',
  Modulo = '__modulo',
  Exponent = '__exponent',
  NestedQuery = '__nested_query',
  EqualTo = '__equal_to',
  NotEqualTo = '__not_equal_to',
  GreaterThan = '__greater_than',
  LessThan = '__less_than',
  GreaterOrEqual = '__greater_or_equal',
  LessOrEqual = '__less_or_equal',

  // MetricsQL
  AscentOverTime = 'ascent_over_time',
  ChangesPrometheus = 'changes_prometheus',
  DecreasesOverTime = 'decreases_over_time',
  DefaultRollup = 'default_rollup',
  DeltaPrometheus = 'delta_prometheus',
  DerivFast = 'deriv_fast',
  DescentOverTime = 'descent_over_time',
  DistinctOverTime = 'distinct_over_time',
  FirstOverTime = 'first_over_time',
  GeomeanOverTime = 'geomean_over_time',
  HistogramOverTime = 'histogram_over_time',
  Ideriv = 'ideriv',
  IncreasePrometheus = 'increase_prometheus',
  IncreasePure = 'increase_pure',
  IncreasesOverTime = 'increases_over_time',
  Integrate = 'integrate',
  Lag = 'lag',
  Lifetime = 'lifetime',
  MadOverTime = 'mad_over_time',
  MedianOverTime = 'median_over_time',
  ModeOverTime = 'mode_over_time',
  RangeOverTime = 'range_over_time',
  RateOverSum = 'rate_over_sum',
  Rollup = 'rollup',
  RollupCandlestick = 'rollup_candlestick',
  RollupDelta = 'rollup_delta',
  RollupDeriv = 'rollup_deriv',
  RollupIncrease = 'rollup_increase',
  RollupRate = 'rollup_rate',
  RollupScrapeInterval = 'rollup_scrape_interval',
  ScrapeInterval = 'scrape_interval',
  StaleSamplesOverTime = 'stale_samples_over_time',
  StdvarOverTime = 'stdvar_over_time',
  Sum2OverTime = 'sum2_over_time',
  TimestampWithName = 'timestamp_with_name',
  TfirstOverTime = 'tfirst_over_time',
  TlastChangeOverTime = 'tlast_change_over_time',
  TlastOverTime = 'tlast_over_time',
  TmaxOverTime = 'tmax_over_time',
  TminOverTime = 'tmin_over_time',
  ZscoreOverTime = 'zscore_over_time',
  HistogramAvg = 'histogram_avg',
  HistogramStddev = 'histogram_stddev',
  HistogramStdvar = 'histogram_stdvar',
  PrometheusBuckets = 'prometheus_buckets',
  Abs = 'abs',
  Interpolate = 'interpolate',
  KeepLastValue = 'keep_last_value',
  KeepNextValue = 'keep_next_value',
  RangeAvg = 'range_avg',
  RangeFirst = 'range_first',
  RangeLast = 'range_last',
  RangeLinearRegression = 'range_linear_regression',
  RangeMad = 'range_mad',
  RangeMax = 'range_max',
  RangeMedian = 'range_median',
  RangeMin = 'range_min',
  RangeStddev = 'range_stddev',
  RangeStdvar = 'range_stdvar',
  RangeSum = 'range_sum',
  RangeZscore = 'range_zscore',
  RemoveResets = 'remove_resets',
  RunningAvg = 'running_avg',
  RunningMax = 'running_max',
  RunningMin = 'running_min',
  RunningSum = 'running_sum',
  Distinct = 'distinct',
  Geomean = 'geomean',
  Histogram = 'histogram',
  BottomkAvg = 'bottomk_avg',
  BottomkLast = 'bottomk_last',
  BottomkMax = 'bottomk_max',
  BottomkMedian = 'bottomk_median',
  BottomkMin = 'bottomk_min',
  TopkAvg = 'topk_avg',
  TopkLast = 'topk_last',
  TopkMax = 'topk_max',
  TopkMedian = 'topk_median',
  TopkMin = 'topk_min',
  Any = 'any',
  Limitk = 'limitk',
  Mad = 'mad',
  Median = 'median',
  Mode = 'mode',
  Share = 'share',
  Stdvar = 'stdvar',
  Sum2 = 'sum2',
  Zscore = 'zscore',
  LabelDel = 'label_del',
  LabelKeep = 'label_keep',
  LabelLowercase = 'label_lowercase',
  LabelUppercase = 'label_uppercase',
  SortByLabel = 'sort_by_label',
  SortByLabelDesc = 'sort_by_label_desc',
  SortByLabelNumeric = 'sort_by_label_numeric',
  SortByLabelNumericDesc = 'sort_by_label_numeric_desc',
  End = 'end',
  Now = 'now',
  Start = 'start',
  Step = 'step',
  CountEqOverTime = 'count_eq_over_time',
  CountGtOverTime = 'count_gt_over_time',
  CountLeOverTime = 'count_le_over_time',
  CountNeOverTime = 'count_ne_over_time',
  DurationOverTime = 'duration_over_time',
  ShareGtOverTime = 'share_gt_over_time',
  ShareLeOverTime = 'share_le_over_time',
  ShareEqOverTime = 'share_eq_over_time',
  BitmapAnd = 'bitmap_and',
  BitmapOr = 'bitmap_or',
  BitmapXor = 'bitmap_xor',
  Rand = 'rand',
  RandExponential = 'rand_exponential',
  RandNormal = 'rand_normal',
  TimezoneOffset = 'timezone_offset',
  LabelSet = 'label_set',
  LabelCopy = 'label_copy',
  LabelMove = 'label_move',
  LabelMap = 'label_map'
}

export interface PromQueryPattern {
  name: string;
  operations: QueryBuilderOperation[];
}
