#!/bin/bash

set -ex

mkdir -p ./dist
indexFile='./dist/index.d.ts'
if [[ -f ${indexFile} ]]; then
    rm ${indexFile}
fi

cat <<EOF >> ${indexFile}
// This file was generated by lezer-metricsql. You probably should not edit it.
import { LRParser } from '@lezer/lr'

export const parser: LRParser
$(sed -E 's/ = [0-9]+/: number/' src/parser.terms.js)
EOF
