services:
  grafana:
    user: root
    container_name: 'victoriametrics-metrics-datasource'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../plugins/victoriametrics-metrics-datasource:/var/lib/grafana/plugins/victoriametrics-metrics-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/victoriametrics-metrics-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.victoriametrics-metrics-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: victoriametrics-metrics-datasource
