victoriametrics-backend-plugin-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker

victoriametrics-backend-plugin-linux-amd64-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker-linux-amd64

victoriametrics-backend-plugin-linux-arm-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker-linux-arm

victoriametrics-backend-plugin-linux-arm64-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker-linux-arm64

victoriametrics-backend-plugin-linux-386-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker-linux-386

victoriametrics-backend-plugin-amd64-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker-darwin-amd64

victoriametrics-backend-plugin-arm64-prod:
	APP_NAME=victoriametrics_backend_plugin $(MAKE) app-via-docker-darwin-arm64
