name: check / backend

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-checks-backend.yml'
      - 'go.*'
      - 'vendor/**'
      - 'pkg/**'
      - '**/Makefile'
      - '**/Magefile.go'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pr-checks-backend.yml'
      - 'go.*'
      - 'vendor/**'
      - 'pkg/**'
      - '**/Makefile'
      - '**/Magefile.go'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          persist-credentials: false
      - name: Restore binaries from cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ./bin
          key: binary
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5.6.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Dependencies
        run: |
          make check-all
          git diff --exit-code
      - name: Prapare binary cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ./bin
          key: binary
  test:
    needs: lint
    strategy:
      matrix:
        scenario: ["golang-test", "golang-test-race"]
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5.6.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: run tests
        run: |
          make ${{ matrix.scenario }}
