name: check / frontend

on:
  push:
    branches: [main]
    paths:
      - '.github/workflow/pr-checks-frontend.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'
      - '**/Makefile'
      - '**/Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflow/pr-checks-frontend.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'
      - '**/Makefile'
      - '**/Dockerfile'

jobs:
  run-check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Set up node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: v24.11.1

      - name: Enable Corepack
        run: corepack enable

      - name: Install all dependencies
        run: yarn install

      - name: Build lezer-metricsql
        run: yarn build:lezer-metricsql

      - name: Run tests
        run: yarn test:ci

      - name: Run typecheck
        run: yarn typecheck