# Name of this action
name: check frontend

# Event triggers on pull request event
# For more detail visit https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
  pull_request:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'

# The jobs this action will run. You can write as many jobs as you want.
# For more detail on this section visit https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  # ID of the job
  run-jest-tests:
    # Name of the job as it will be displayed in GitHub
    name: Jest Tests
    # Machine which this action will be run on. For a list of all the machines available/how to run on self hosted machine visit
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # Steps this job must take to complete
    steps:
      # Reference the main branch. For more information visit https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      # Specify which version of Node this project is using. For more information visit.
      # https://docs.github.com/en/actions/guides/building-and-testing-nodejs#specifying-the-nodejs-version
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 18.13.0

      - name: Install all dependencies
        run: yarn install

      - name: Run Jest Tests
        run: npm run test

  run-build:
    needs: run-jest-tests
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 18.13.0

      - name: Install all dependencies
        run: yarn install

      - name: Build
        shell: 'script -q -e -c "bash {0}"'
        run: |
          make victoriametrics-frontend-plugin-build
