name: check / plugin
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-checks-plugin.yml'
      - 'go.*'
      - 'vendor/**'
      - 'pkg/**'
      - '**/Makefile'
      - '**/Magefile.go'
      - '**/Dockerfile'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pr-checks-plugin.yml'
      - 'go.*'
      - 'vendor/**'
      - 'pkg/**'
      - '**/Makefile'
      - '**/Magefile.go'
      - '**/Dockerfile'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build and validate
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5.6.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Set up node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: v24.11.1

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node caches
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: |
            ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
        run: |
          make vm-plugin-check
